version: "3"

services:
  db:
    image: postgres:13-buster
    restart: always
    container_name: geye-db
    volumes:
      - ./run/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: geye
      POSTGRES_USER: geye
  webapp:
    build: .
    ports:
      - "7001:8000"
    container_name: geye-web
    volumes:
      - ./run/web:/app/logs
    depends_on:
      - db
    environment:
      DB_NAME: geye
      DB_USER: geye
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 15432
