# Generated by Django 2.1.2 on 2018-10-22 21:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeyeFilterRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('rule_type', models.PositiveSmallIntegerField(default=0)),
                ('rule_engine', models.PositiveSmallIntegerField(default=0)),
                ('rule', models.TextField()),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('parent_id', models.BigIntegerField(default=0)),
                ('action', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=5)),
            ],
            options={
                'db_table': 'geye_filter_rule',
            },
        ),
        migrations.CreateModel(
            name='GeyeLeaksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('repo_name', models.CharField(db_index=True, default='', max_length=256)),
                ('author', models.CharField(default='', max_length=256)),
                ('path', models.CharField(default='', max_length=1024)),
                ('filename', models.CharField(default='', max_length=256)),
                ('sha', models.CharField(db_index=True, default='', max_length=40)),
                ('full_code_url', models.TextField()),
                ('url', models.TextField()),
                ('code', models.TextField()),
                ('srid', models.BigIntegerField(default=0)),
                ('frid', models.BigIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('pushed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geye_leaks',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GeyeSearchRuleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('rule', models.CharField(default='', max_length=1024)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('last_refresh_time', models.DateTimeField(auto_now_add=True)),
                ('delay', models.PositiveIntegerField(default=5)),
                ('need_notification', models.BooleanField(default=False)),
                ('clone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geye_search_rule',
            },
        ),
        migrations.CreateModel(
            name='GeyeTokenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('token_name', models.CharField(default='TokenName', max_length=32)),
                ('token', models.CharField(default='', max_length=64)),
                ('remain_limit', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'geye_token',
            },
        ),
    ]
