# Generated by Django 2.1.2 on 2018-12-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeyeMonitorResultsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('monitor_rule_id', models.BigIntegerField(default=0)),
                ('event_id', models.BigIntegerField(default=0)),
                ('event_type', models.CharField(default='', max_length=128)),
                ('actor_url', models.CharField(default='', max_length=512)),
                ('actor_login', models.CharField(default='', max_length=128)),
                ('actor_display_name', models.CharField(default='', max_length=128)),
                ('org_url', models.CharField(default='', max_length=512)),
                ('org_name', models.CharField(default='', max_length=128)),
                ('repo_url', models.CharField(default='', max_length=512)),
                ('repo_name', models.CharField(default='', max_length=128)),
                ('content', models.TextField()),
                ('event_created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geye_monitor_results',
            },
        ),
        migrations.CreateModel(
            name='GeyeMonitorRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task_type', models.CharField(default='', max_length=32)),
                ('event_type', models.CharField(default='', max_length=128)),
                ('rule_content', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=5)),
                ('last_fetch_time', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=5)),
            ],
            options={
                'db_table': 'geye_monitor_rules',
            },
        ),
        migrations.AlterModelManagers(
            name='geyeleaksmodel',
            managers=[
            ],
        ),
    ]
