# Generated by Django 3.2.5 on 2021-10-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181223_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeyeUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('username', models.CharField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=512)),
                ('email', models.CharField(default='', max_length=128)),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'geye_user',
            },
        ),
        migrations.CreateModel(
            name='GeyeYuqueSearchRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('rule', models.CharField(default='', max_length=1024)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=5)),
                ('last_refresh_time', models.DateTimeField(auto_now_add=True)),
                ('interval', models.PositiveIntegerField(default=5)),
                ('need_notification', models.PositiveSmallIntegerField(default=0)),
                ('need_save', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geye_yuque_search_rule',
            },
        ),
        migrations.AlterField(
            model_name='geyefilterrulemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geyeleaksmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geyemonitorresultsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geyemonitorrules',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geyemonitorrules',
            name='task_type',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='geyesearchrulemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='geyetokenmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
